spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=anime
    username: root
    password: root
logging:
  level:
    io.r2dbc.postgresql: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG